In [2]:
import pandas as pd
import numpy as np

In [3]:
books  = pd.read_csv("Books.csv")
users  = pd.read_csv("Users.csv")
ratings  = pd.read_csv("Ratings.csv")

C:\Users\Nitro\AppData\Local\Temp\ipykernel_29492\4249740469.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books  = pd.read_csv("Books.csv")

In [4]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [5]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
"ratings.head()"

'ratings.head()'

In [9]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [10]:
books.shape

(271360, 8)

In [11]:
users.shape

(278858, 3)

In [12]:
ratings.shape

(1149780, 3)

In [13]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [14]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [15]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [16]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [17]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [18]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [19]:
books.duplicated().sum()

0

In [20]:
users.duplicated().sum()

0

In [21]:
books.duplicated().sum()

0

In [22]:
ratings.duplicated().sum()

0

In [23]:
users.duplicated().sum()

0

# Popularity based recommendation

In [24]:
ratings.merge(books,on ="ISBN").shape

(1031136, 10)

In [25]:
books.keys()

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [26]:
ratings.keys()

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [27]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [28]:
ratings.merge(books,on ="ISBN")

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [29]:
ratings_books = ratings.merge(books,on ="ISBN")

In [30]:
ratings_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [31]:
rating_books_num = ratings_books.groupby("Book-Title").count()["Book-Rating"].reset_index()
rating_books_num

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ãƒ?Ã‚?lpiraten.            2
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.            4
241068                                Ãƒ?Ã‚?sterlich leben.            1
241069                              Ãƒ?Ã‚?stlich der Berge.            3
241070                                  Ãƒ?Ã‚?thique en toc            2

[241071 rows x 2 columns]

In [32]:
rating_books_num.rename(columns = {'Book-Rating':'Book-Rating-In-Numbers'}, inplace = True)
rating_books_num

,Book-Title,Book-Rating-In-Numbers
0,A Light in the Storm: The Civil War Diary of ...,4
1,Always Have Popsicles,1
2,Apple Magic (The Collector's series),1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1
4,Beyond IBM: Leadership Marketing and Finance ...,1
...,...,...
241066,Ãƒ?Ã‚?lpiraten.,2
241067,Ãƒ?Ã‚?rger mit Produkt X. Roman.,4
241068,Ãƒ?Ã‚?sterlich leben.,1
241069,Ãƒ?Ã‚?stlich der Berge.,3
241070,Ãƒ?Ã‚?thique en toc,2

In [33]:
rating_books_avg = ratings_books.groupby("Book-Title").mean()["Book-Rating"].reset_index()

C:\Users\Nitro\AppData\Local\Temp\ipykernel_29492\788844077.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  rating_books_avg = ratings_books.groupby("Book-Title").mean()["Book-Rating"].reset_index()

In [34]:
rating_books_avg.rename(columns = {"Book-Rating":"Average-Book-Rating"},inplace = True)
rating_books_avg

                                               Book-Title  Average-Book-Rating
0        A Light in the Storm: The Civil War Diary of ...             2.250000
1                                   Always Have Popsicles             0.000000
2                    Apple Magic (The Collector's series)             0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...             8.000000
4        Beyond IBM: Leadership Marketing and Finance ...             0.000000
...                                                   ...                  ...
241066                                      Ãƒ?Ã‚?lpiraten.             0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.             5.250000
241068                                Ãƒ?Ã‚?sterlich leben.             7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.             2.666667
241070                                  Ãƒ?Ã‚?thique en toc             4.000000

[241071 rows x 2 columns]

In [35]:
rating_books_avg.rename(columns = {"Book-Rating":"Average-Book-Rating"},inplace = True)

In [36]:
rating_books_avg

                                               Book-Title  Average-Book-Rating
0        A Light in the Storm: The Civil War Diary of ...             2.250000
1                                   Always Have Popsicles             0.000000
2                    Apple Magic (The Collector's series)             0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...             8.000000
4        Beyond IBM: Leadership Marketing and Finance ...             0.000000
...                                                   ...                  ...
241066                                      Ãƒ?Ã‚?lpiraten.             0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.             5.250000
241068                                Ãƒ?Ã‚?sterlich leben.             7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.             2.666667
241070                                  Ãƒ?Ã‚?thique en toc             4.000000

[241071 rows x 2 columns]

In [37]:
rating_books_avg.rename(columns = {"Average-Book-Rating=":"Average-Book-Rating"},inplace = True)

In [38]:
rating_books_avg

                                               Book-Title  Average-Book-Rating
0        A Light in the Storm: The Civil War Diary of ...             2.250000
1                                   Always Have Popsicles             0.000000
2                    Apple Magic (The Collector's series)             0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...             8.000000
4        Beyond IBM: Leadership Marketing and Finance ...             0.000000
...                                                   ...                  ...
241066                                      Ãƒ?Ã‚?lpiraten.             0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.             5.250000
241068                                Ãƒ?Ã‚?sterlich leben.             7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.             2.666667
241070                                  Ãƒ?Ã‚?thique en toc             4.000000

[241071 rows x 2 columns]

In [39]:
popular_data_frame = rating_books_num.merge(rating_books_avg, on  = "Book-Title")

In [40]:
popular_data_frame

,Book-Title,Book-Rating-In-Numbers,Average-Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ãƒ?Ã‚?lpiraten.,2,0.000000
241067,Ãƒ?Ã‚?rger mit Produkt X. Roman.,4,5.250000
241068,Ãƒ?Ã‚?sterlich leben.,1,7.000000
241069,Ãƒ?Ã‚?stlich der Berge.,3,2.666667
241070,Ãƒ?Ã‚?thique en toc,2,4.000000

In [41]:
popular_books = popular_data_frame[popular_data_frame["Book-Rating-In-Numbers"] >=250].sort_values("Average-Book-Rating",ascending = False).head(50)

In [42]:
popular_books

,Book-Title,Book-Rating-In-Numbers,Average-Book-Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [43]:
All_books_dataframe = popular_books.merge(books,on= "Book-Title")
popular_books_dataframe = All_books_dataframe.drop_duplicates("Book-Title")[["Book-Title","Book-Author","Image-URL-M","Book-Rating-In-Numbers","Average-Book-Rating"]]


## Top 10  Popular books with highest average rating

In [44]:
popular_books = popular_books_dataframe[1:10]
popular_books.groupby("Book-Title")

In [45]:
import pickle

In [46]:
pickle.dump(popular_books.to_dict(),open("popular_books.pkl", "wb"))

## Collaborative filtering based recommendation system

In [47]:
rating_user = ratings_books.groupby("User-ID").count()["Book-Rating"] >200
rating_index_user = rating_user[rating_user].index
rating_index_user

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=811)

In [48]:
ratings_books["User-ID"]

0          276725
1            2313
2            6543
3            8680
4           10314
            ...
1031131    276688
1031132    276688
1031133    276690
1031134    276704
1031135    276704
Name: User-ID, Length: 1031136, dtype: int64

In [49]:
filtered_rating_user = ratings_books[ratings_books["User-ID"].isin(rating_index_user)]
filtered_rating_user

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃƒ?Ã‚Â¤fin SchÃƒ?Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [50]:
relevant_books = filtered_rating_user.groupby("Book-Title").count()["Book-Rating"]>=50
relevant_books = relevant_books[relevant_books].index

In [51]:
relevant_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [52]:
famous_books = filtered_rating_user[filtered_rating_user["Book-Title"].isin(relevant_books)]
famous_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [53]:
famous_books = famous_books.drop(columns = ["Image-URL-S","Image-URL-M","Image-URL-L"])

In [54]:
famous_books["Book-Title"].duplicated().sum()

57880

In [55]:
famous_books = famous_books.drop_duplicates(subset=['Book-Title'])

In [56]:
famous_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,8681,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam
750,278418,055356451X,0,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...,...,...
457242,11676,0345413865,0,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,11676,0373483694,0,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,11676,0399144714,9,Vector,Robin Cook,1999,Putnam Pub Group
479476,11676,0553278029,8,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,11676,0743418131,0,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket

In [57]:
pivited_table = famous_books.pivot_table( index = "Book-Title",columns = "User-ID",values = "Book-Rating")
pivited_table.fillna(0,inplace = True)
pivited_table

User-ID,254,2276,2766,2977,3363,4017,6251,6323,6543,6563,...,60244,62895,82893,112881,132083,142093,234623,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
import pickle

In [59]:
pickle.dump(famous_books.to_dict(),open("famous_books_dict.pkl","wb"))

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
similarity_score = cosine_similarity(pivited_table)

In [62]:
pickle.dump(similarity_score,open("similarity_collab.pkl","wb"))

In [63]:
pickle.dump(pivited_table,open("pivited_table.pkl","wb"))

In [64]:
np.where(pivited_table.index == "Fahrenheit 451")[0][0]

181

In [65]:
np.where(pivited_table.index=="Vector")

(array([664], dtype=int64),)

In [66]:
def recommend_user(book):
    index = np.where(pivited_table.index==book)[0][0]
    filtered_books = sorted(list(enumerate(similarity_score[index])),key = lambda x: x[1],reverse = True)[1:6]
    collaborative_list = []
    for i in filtered_books:
        collaborative_list.append(pivited_table.index[(i[0])])
    return collaborative_list

## 5 Books based on  similar user feedback

In [67]:
recommend_user("Vector")

['A Great Deliverance',
 'Absolute Power',
 'Angels &amp; Demons',
 'Before I Say Good-Bye',
 'Brave New World']

# Content Based Recommendation System

In [68]:
famous_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,8681,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam
750,278418,055356451X,0,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...,...,...
457242,11676,0345413865,0,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,11676,0373483694,0,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,11676,0399144714,9,Vector,Robin Cook,1999,Putnam Pub Group
479476,11676,0553278029,8,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,11676,0743418131,0,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket

In [69]:
famous_books.head(4)

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,8681,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam

In [70]:
famous_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,8681,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam
750,278418,055356451X,0,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...,...,...
457242,11676,0345413865,0,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,11676,0373483694,0,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,11676,0399144714,9,Vector,Robin Cook,1999,Putnam Pub Group
479476,11676,0553278029,8,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,11676,0743418131,0,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket

In [71]:
famous_books.dropna(inplace = True)

In [72]:
relevant_books_data = famous_books.drop(columns = ["User-ID","Book-Rating"])

In [73]:
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,0446520802,The Notebook,Nicholas Sparks,1996,Warner Books
184,038550120X,A Painted House,JOHN GRISHAM,2001,Doubleday
368,0425115801,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,0553561618,Dark Paradise,TAMI HOAG,1994,Bantam
750,055356451X,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,0373483694,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,0399144714,Vector,Robin Cook,1999,Putnam Pub Group
479476,0553278029,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,0743418131,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket

In [74]:
relevant_books_data.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
dtype: int64

In [75]:
relevant_books_data.duplicated().sum()

0

In [76]:
relevant_books_data.drop_duplicates(inplace = True)
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,0446520802,The Notebook,Nicholas Sparks,1996,Warner Books
184,038550120X,A Painted House,JOHN GRISHAM,2001,Doubleday
368,0425115801,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,0553561618,Dark Paradise,TAMI HOAG,1994,Bantam
750,055356451X,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,0373483694,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,0399144714,Vector,Robin Cook,1999,Putnam Pub Group
479476,0553278029,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,0743418131,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket

In [77]:
relevant_books_data["Year-Of-Publication"]

63        1996
184       2001
368       1996
616       1994
750       1995
          ...
457242    1999
458903    1998
465107    1999
479476    1989
489034    2002
Name: Year-Of-Publication, Length: 706, dtype: object

In [78]:
relevant_books_data["Book-Author"].apply(lambda x:x.replace(" ","") )

63           NicholasSparks
184             JOHNGRISHAM
368            DeanR.Koontz
616                TAMIHOAG
750                TAMIHOAG
                ...
457242    JONATHANKELLERMAN
458903          NoraRoberts
465107            RobinCook
479476      ElizabethGeorge
489034     MaryHigginsClark
Name: Book-Author, Length: 706, dtype: object

In [79]:

relevant_books_data["Book-Author"] = relevant_books_data["Book-Author"].apply(lambda x:x.replace(" ","") )

In [80]:
relevant_books_data["Publisher"] = relevant_books_data["Publisher"].apply(lambda x:x.replace(" ",""))

In [81]:
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,0446520802,The Notebook,NicholasSparks,1996,WarnerBooks
184,038550120X,A Painted House,JOHNGRISHAM,2001,Doubleday
368,0425115801,Lightning,DeanR.Koontz,1996,BerkleyPublishingGroup
616,0553561618,Dark Paradise,TAMIHOAG,1994,Bantam
750,055356451X,Night Sins,TAMIHOAG,1995,Bantam
...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHANKELLERMAN,1999,BallantineBooks
458903,0373483694,Macgregor Grooms (Macgregors),NoraRoberts,1998,Silhouette
465107,0399144714,Vector,RobinCook,1999,PutnamPubGroup
479476,0553278029,A Great Deliverance,ElizabethGeorge,1989,BantamBooks
489034,0743418131,Deck the Halls (Holiday Classics),MaryHigginsClark,2002,Pocket

In [82]:
relevant_books_data["Title"] = relevant_books_data["Book-Title"].apply(lambda x:x.replace(" ",""))
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Title
63,0446520802,The Notebook,NicholasSparks,1996,WarnerBooks,TheNotebook
184,038550120X,A Painted House,JOHNGRISHAM,2001,Doubleday,APaintedHouse
368,0425115801,Lightning,DeanR.Koontz,1996,BerkleyPublishingGroup,Lightning
616,0553561618,Dark Paradise,TAMIHOAG,1994,Bantam,DarkParadise
750,055356451X,Night Sins,TAMIHOAG,1995,Bantam,NightSins
...,...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHANKELLERMAN,1999,BallantineBooks,BillyStraight:ANovel
458903,0373483694,Macgregor Grooms (Macgregors),NoraRoberts,1998,Silhouette,MacgregorGrooms(Macgregors)
465107,0399144714,Vector,RobinCook,1999,PutnamPubGroup,Vector
479476,0553278029,A Great Deliverance,ElizabethGeorge,1989,BantamBooks,AGreatDeliverance
489034,0743418131,Deck the Halls (Holiday Classics),MaryHigginsClark,2002,Pocket,DecktheHalls(HolidayClassics)

In [83]:
relevant_books_data["Year-Of-Publication"] = relevant_books_data["Year-Of-Publication"].apply(str)
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Title
63,0446520802,The Notebook,NicholasSparks,1996,WarnerBooks,TheNotebook
184,038550120X,A Painted House,JOHNGRISHAM,2001,Doubleday,APaintedHouse
368,0425115801,Lightning,DeanR.Koontz,1996,BerkleyPublishingGroup,Lightning
616,0553561618,Dark Paradise,TAMIHOAG,1994,Bantam,DarkParadise
750,055356451X,Night Sins,TAMIHOAG,1995,Bantam,NightSins
...,...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHANKELLERMAN,1999,BallantineBooks,BillyStraight:ANovel
458903,0373483694,Macgregor Grooms (Macgregors),NoraRoberts,1998,Silhouette,MacgregorGrooms(Macgregors)
465107,0399144714,Vector,RobinCook,1999,PutnamPubGroup,Vector
479476,0553278029,A Great Deliverance,ElizabethGeorge,1989,BantamBooks,AGreatDeliverance
489034,0743418131,Deck the Halls (Holiday Classics),MaryHigginsClark,2002,Pocket,DecktheHalls(HolidayClassics)

In [84]:
relevant_books_data["Tags"] = relevant_books_data["Title"] + " "+ relevant_books_data["Book-Author"] + " "+ relevant_books_data["Publisher"]+ " "+ relevant_books_data["Year-Of-Publication"]
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Title,Tags
63,0446520802,The Notebook,NicholasSparks,1996,WarnerBooks,TheNotebook,TheNotebook NicholasSparks WarnerBooks 1996
184,038550120X,A Painted House,JOHNGRISHAM,2001,Doubleday,APaintedHouse,APaintedHouse JOHNGRISHAM Doubleday 2001
368,0425115801,Lightning,DeanR.Koontz,1996,BerkleyPublishingGroup,Lightning,Lightning DeanR.Koontz BerkleyPublishingGroup ...
616,0553561618,Dark Paradise,TAMIHOAG,1994,Bantam,DarkParadise,DarkParadise TAMIHOAG Bantam 1994
750,055356451X,Night Sins,TAMIHOAG,1995,Bantam,NightSins,NightSins TAMIHOAG Bantam 1995
...,...,...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHANKELLERMAN,1999,BallantineBooks,BillyStraight:ANovel,BillyStraight:ANovel JONATHANKELLERMAN Ballant...
458903,0373483694,Macgregor Grooms (Macgregors),NoraRoberts,1998,Silhouette,MacgregorGrooms(Macgregors),MacgregorGrooms(Macgregors) NoraRoberts Silhou...
465107,0399144714,Vector,RobinCook,1999,PutnamPubGroup,Vector,Vector RobinCook PutnamPubGroup 1999
479476,0553278029,A Great Deliverance,ElizabethGeorge,1989,BantamBooks,AGreatDeliverance,AGreatDeliverance ElizabethGeorge BantamBooks ...
489034,0743418131,Deck the Halls (Holiday Classics),MaryHigginsClark,2002,Pocket,DecktheHalls(HolidayClassics),DecktheHalls(HolidayClassics) MaryHigginsClark...

In [85]:
relevant_books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Title,Tags
63,0446520802,The Notebook,NicholasSparks,1996,WarnerBooks,TheNotebook,TheNotebook NicholasSparks WarnerBooks 1996
184,038550120X,A Painted House,JOHNGRISHAM,2001,Doubleday,APaintedHouse,APaintedHouse JOHNGRISHAM Doubleday 2001
368,0425115801,Lightning,DeanR.Koontz,1996,BerkleyPublishingGroup,Lightning,Lightning DeanR.Koontz BerkleyPublishingGroup ...
616,0553561618,Dark Paradise,TAMIHOAG,1994,Bantam,DarkParadise,DarkParadise TAMIHOAG Bantam 1994
750,055356451X,Night Sins,TAMIHOAG,1995,Bantam,NightSins,NightSins TAMIHOAG Bantam 1995
...,...,...,...,...,...,...,...
457242,0345413865,Billy Straight : A Novel,JONATHANKELLERMAN,1999,BallantineBooks,BillyStraight:ANovel,BillyStraight:ANovel JONATHANKELLERMAN Ballant...
458903,0373483694,Macgregor Grooms (Macgregors),NoraRoberts,1998,Silhouette,MacgregorGrooms(Macgregors),MacgregorGrooms(Macgregors) NoraRoberts Silhou...
465107,0399144714,Vector,RobinCook,1999,PutnamPubGroup,Vector,Vector RobinCook PutnamPubGroup 1999
479476,0553278029,A Great Deliverance,ElizabethGeorge,1989,BantamBooks,AGreatDeliverance,AGreatDeliverance ElizabethGeorge BantamBooks ...
489034,0743418131,Deck the Halls (Holiday Classics),MaryHigginsClark,2002,Pocket,DecktheHalls(HolidayClassics),DecktheHalls(HolidayClassics) MaryHigginsClark...

In [86]:
books_with_tags = relevant_books_data.drop(columns = (["Book-Author","Publisher","Year-Of-Publication","Title"]))

In [87]:
books_with_tags = books_with_tags.drop_duplicates(subset=['Book-Title'])
books_with_tag_based = books_with_tags.drop_duplicates(subset=['Tags'])
books_with_tag_based

,ISBN,Book-Title,Tags
63,0446520802,The Notebook,TheNotebook NicholasSparks WarnerBooks 1996
184,038550120X,A Painted House,APaintedHouse JOHNGRISHAM Doubleday 2001
368,0425115801,Lightning,Lightning DeanR.Koontz BerkleyPublishingGroup ...
616,0553561618,Dark Paradise,DarkParadise TAMIHOAG Bantam 1994
750,055356451X,Night Sins,NightSins TAMIHOAG Bantam 1995
...,...,...,...
457242,0345413865,Billy Straight : A Novel,BillyStraight:ANovel JONATHANKELLERMAN Ballant...
458903,0373483694,Macgregor Grooms (Macgregors),MacgregorGrooms(Macgregors) NoraRoberts Silhou...
465107,0399144714,Vector,Vector RobinCook PutnamPubGroup 1999
479476,0553278029,A Great Deliverance,AGreatDeliverance ElizabethGeorge BantamBooks ...
489034,0743418131,Deck the Halls (Holiday Classics),DecktheHalls(HolidayClassics) MaryHigginsClark...

In [88]:
from sklearn.feature_extraction.text import CountVectorizer

In [89]:
cv  = CountVectorizer(stop_words = "english", max_features = 1000)

In [90]:
books_with_tags["Tags"]

63              TheNotebook NicholasSparks WarnerBooks 1996
184                APaintedHouse JOHNGRISHAM Doubleday 2001
368       Lightning DeanR.Koontz BerkleyPublishingGroup ...
616                       DarkParadise TAMIHOAG Bantam 1994
750                          NightSins TAMIHOAG Bantam 1995
                                ...
457242    BillyStraight:ANovel JONATHANKELLERMAN Ballant...
458903    MacgregorGrooms(Macgregors) NoraRoberts Silhou...
465107                 Vector RobinCook PutnamPubGroup 1999
479476    AGreatDeliverance ElizabethGeorge BantamBooks ...
489034    DecktheHalls(HolidayClassics) MaryHigginsClark...
Name: Tags, Length: 706, dtype: object

In [91]:
books_with_tags.duplicated().sum()

0

In [92]:
books_with_tags["Tags"].duplicated().sum()

0

In [93]:
books_with_tags["Book-Title"].duplicated().sum()

0

In [94]:
books_with_tags.drop_duplicates(subset="Tags", inplace=True)

In [95]:
books_with_tags.drop_duplicates(subset="Book-Title", inplace=True)

In [96]:
books_with_tags.dropna(inplace = True)

In [97]:
books_with_tags.shape

(706, 3)

In [98]:
dense_array = cv.fit_transform(books_with_tags["Tags"])
vectors = dense_array.toarray()

In [99]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [100]:
books_with_tags["Book-Title"]

63                             The Notebook
184                         A Painted House
368                               Lightning
616                           Dark Paradise
750                              Night Sins
                        ...
457242             Billy Straight : A Novel
458903        Macgregor Grooms (Macgregors)
465107                               Vector
479476                  A Great Deliverance
489034    Deck the Halls (Holiday Classics)
Name: Book-Title, Length: 706, dtype: object

In [101]:
books_with_tags

,ISBN,Book-Title,Tags
63,0446520802,The Notebook,TheNotebook NicholasSparks WarnerBooks 1996
184,038550120X,A Painted House,APaintedHouse JOHNGRISHAM Doubleday 2001
368,0425115801,Lightning,Lightning DeanR.Koontz BerkleyPublishingGroup ...
616,0553561618,Dark Paradise,DarkParadise TAMIHOAG Bantam 1994
750,055356451X,Night Sins,NightSins TAMIHOAG Bantam 1995
...,...,...,...
457242,0345413865,Billy Straight : A Novel,BillyStraight:ANovel JONATHANKELLERMAN Ballant...
458903,0373483694,Macgregor Grooms (Macgregors),MacgregorGrooms(Macgregors) NoraRoberts Silhou...
465107,0399144714,Vector,Vector RobinCook PutnamPubGroup 1999
479476,0553278029,A Great Deliverance,AGreatDeliverance ElizabethGeorge BantamBooks ...
489034,0743418131,Deck the Halls (Holiday Classics),DecktheHalls(HolidayClassics) MaryHigginsClark...

In [102]:
vectors[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [103]:
vectors.shape

(706, 1000)

In [104]:
len(cv.get_feature_names_out())

1000

In [105]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\nitro\anaconda3\lib\site-packages (3.7)
Requirement already satisfied: click in c:\users\nitro\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\nitro\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\nitro\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\nitro\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\nitro\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [106]:
import nltk

In [107]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

In [108]:
def stems(tags):
    y= []
    for i in tags.split():
        y.append(stemmer.stem(i))
    return " ".join(y)

In [109]:
books_with_tags["Tags"] = books_with_tags["Tags"].apply(stems)

In [110]:
books_with_tags

,ISBN,Book-Title,Tags
63,0446520802,The Notebook,thenotebook nicholasspark warnerbook 1996
184,038550120X,A Painted House,apaintedhous johngrisham doubleday 2001
368,0425115801,Lightning,lightn deanr.koontz berkleypublishinggroup 1996
616,0553561618,Dark Paradise,darkparadis tamihoag bantam 1994
750,055356451X,Night Sins,nightsin tamihoag bantam 1995
...,...,...,...
457242,0345413865,Billy Straight : A Novel,billystraight:anovel jonathankellerman ballant...
458903,0373483694,Macgregor Grooms (Macgregors),macgregorgrooms(macgregors) norarobert silhoue...
465107,0399144714,Vector,vector robincook putnampubgroup 1999
479476,0553278029,A Great Deliverance,agreatdeliver elizabethgeorg bantambook 1989
489034,0743418131,Deck the Halls (Holiday Classics),deckthehalls(holidayclassics) maryhigginsclark...

In [111]:
similarity = cosine_similarity(vectors)

In [112]:
def recommendation_content(book):
    index = books_with_tags[books_with_tags["Book-Title"]==book].index[0]
    distances = similarity[index]
    movies_list= sorted(list(enumerate(distances)),key = lambda x:x[1], reverse = True)[1:6]
    content_list = []
    for i in movies_list:
        content_list.append(books_with_tags.iloc[i[0]]["Book-Title"])
    return content_list

In [113]:
books_with_tags.values

array([['0446520802', 'The Notebook',
        'thenotebook nicholasspark warnerbook 1996'],
       ['038550120X', 'A Painted House',
        'apaintedhous johngrisham doubleday 2001'],
       ['0425115801', 'Lightning',
        'lightn deanr.koontz berkleypublishinggroup 1996'],
       ...,
       ['0399144714', 'Vector', 'vector robincook putnampubgroup 1999'],
       ['0553278029', 'A Great Deliverance',
        'agreatdeliver elizabethgeorg bantambook 1989'],
       ['0743418131', 'Deck the Halls (Holiday Classics)',
        'deckthehalls(holidayclassics) maryhigginsclark pocket 2002']],
      dtype=object)

## Top 5 book recommendation based on content

In [114]:
recommendation_content("A Painted House")

['\\O\\" Is for Outlaw"',
 "Drowning Ruth (Oprah's Book Club)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'A Widow for One Year',
 'Icy Sparks']

# Recommendation System based on Hybrid Approach

In [115]:
def hybrid_recommendation(book):
    hybrid = recommendation_content(book) + recommend_user(book)
    hybrid_based = set(hybrid)
    strin =  '\n'.join(hybrid_based)
    return strin

In [116]:
result = hybrid_recommendation("The Notebook")
print(result)

Violets Are Blue
A Case of Need
When the Wind Blows
The Switch
1st to Die: A Novel
2nd Chance
4 Blondes
A Bend in the Road
Roses Are Red (Alex Cross Novels)

In [117]:
books_with_tags

,ISBN,Book-Title,Tags
63,0446520802,The Notebook,thenotebook nicholasspark warnerbook 1996
184,038550120X,A Painted House,apaintedhous johngrisham doubleday 2001
368,0425115801,Lightning,lightn deanr.koontz berkleypublishinggroup 1996
616,0553561618,Dark Paradise,darkparadis tamihoag bantam 1994
750,055356451X,Night Sins,nightsin tamihoag bantam 1995
...,...,...,...
457242,0345413865,Billy Straight : A Novel,billystraight:anovel jonathankellerman ballant...
458903,0373483694,Macgregor Grooms (Macgregors),macgregorgrooms(macgregors) norarobert silhoue...
465107,0399144714,Vector,vector robincook putnampubgroup 1999
479476,0553278029,A Great Deliverance,agreatdeliver elizabethgeorg bantambook 1989
489034,0743418131,Deck the Halls (Holiday Classics),deckthehalls(holidayclassics) maryhigginsclark...

In [118]:
import pickle

In [119]:
books_with_tags["Book-Title"].values

array(['The Notebook', 'A Painted House', 'Lightning', 'Dark Paradise',
       'Night Sins', 'How Stella Got Her Groove Back',
       'Waiting to Exhale', 'The Pillars of the Earth', 'The Dark Half',
       'Harry Potter and the Order of the Phoenix (Book 5)',
       'False Memory', "Bridget Jones's Diary", 'A Wrinkle In Time',
       'The Boy Next Door', 'Artemis Fowl (Artemis Fowl, Book 1)',
       'The Last Time They Met : A Novel',
       'Along Came a Spider (Alex Cross Novels)', 'Whispers',
       "Ender's Game (Ender Wiggins Saga (Paperback))", 'The Jester',
       'The King of Torts',
       'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
       'Matilda', 'The Lovely Bones: A Novel', 'The Da Vinci Code',
       'The Joy Luck Club', 'Wild Animus', 'Coraline',
       'Harry Potter and the Chamber of Secrets (Book 2)',
       "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
       'To Kill a Mockingbird', 'Four To Score (A Stephanie Plum Novel)',
       'Southern Cross', 'The Chamber',
       "The Idiot Girls' Action Adventure Club", 'Dreamcatcher',
       'All Around the Town', 'Winter Solstice', 'Deja Dead',
       'The Saving Graces: A Novel',
       "Full House (Janet Evanovich's Full Series)", 'Mystic River',
       'Roses Are Red (Alex Cross Novels)', 'Violets Are Blue',
       "The Sweet Potato Queens' Book of Love",
       "She's Come Undone (Oprah's Book Club (Paperback))", 'Choke',
       'Hannibal',
       'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
       'The Summons', 'Mortal Prey', 'Fahrenheit 451', 'Flesh and Blood',
       'I Is for Innocent', 'Back Roads', 'Silent Witness',
       'Angels &amp; Demons', 'Black Notice', 'The Street Lawyer',
       'The Bourne Supremacy', 'Bag of Bones', 'The Green Mile',
       'Big Trouble', 'Cradle and All', '1st to Die: A Novel',
       'Over the Edge', 'Sleepers', 'The Hot Zone', 'A Man in Full',
       "The Bonesetter's Daughter", 'Holes (Yearling Newbery)',
       'The Girl Who Loved Tom Gordon', 'The English Patient',
       "I Know This Much Is True (Oprah's Book Club)",
       'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       'I Know This Much Is True', "Fortune's Rocks : A Novel",
       'The Blind Assassin', 'Breathing Lessons', 'The Brethren',
       'Jack &amp; Jill (Alex Cross Novels)',
       'Cat &amp; Mouse (Alex Cross Novels)', 'Dances With Wolves',
       'The Prince of Tides', 'The Alienist',
       "She's Come Undone (Oprah's Book Club)", 'SHIPPING NEWS',
       'Girl, Interrupted',
       'A Child Called \\It\\": One Child\'s Courage to Survive"',
       'The Beach House', 'White Teeth: A Novel', "Daddy's Little Girl",
       "The Hitchhiker's Guide to the Galaxy", 'The Stone Diaries',
       'Girl in Hyacinth Blue', 'The Devil Wears Prada : A Novel',
       'While I Was Gone', "The Pilot's Wife : A Novel",
       'Girl with a Pearl Earring', 'Chocolat', "From Potter's Field",
       'Little Altars Everywhere: A Novel',
       'On the Street Where You Live', 'Life of Pi',
       'The Red Tent (Bestselling Backlist)',
       'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
       'A Walk to Remember', 'Thinner', 'I Know Why the Caged Bird Sings',
       'Bridget Jones : The Edge of Reason', 'The Temple of My Familiar',
       "Angela's Ashes (MMP) : A Memoir", 'The Poisonwood Bible: A Novel',
       'Bel Canto: A Novel',
       'One for the Money (Stephanie Plum Novels (Paperback))',
       'The Secret Garden', 'The Tao of Pooh', 'The Secret Life of Bees',
       'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       "Full Tilt (Janet Evanovich's Full Series)", 'Lucky : A Memoir',
       'The Dogs of Babel (Today Show Book Club #12)',
       "White Oleander : A Novel (Oprah's Book Club)",
       'White Oleander : A Novel', 'Me Talk Pretty One Day', 'Naked',
       'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
       'A Prayer for Owen Meany', 'No Safe Place', 'The Murder Book',
       'Middlesex: A Novel', 'Postmortem',
       'All That Remains (Kay Scarpetta Mysteries (Paperback))',
       'The Rainmaker',
       "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
       'Into the Wild', 'Oryx and Crake', 'Lord of the Flies', 'Watchers',
       'Mortal Fear', 'The Cardinal of the Kremlin (Jack Ryan Novels)',
       'Rules of Prey', 'Mind Prey', 'Contagion', 'Cause of Death',
       'Certain Prey',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       "Harry Potter and the Sorcerer's Stone (Book 1)", 'The Promise',
       'Secrets', 'Wanderlust', 'Guardian Angel', 'Vanished',
       'The Partner', 'Tell No One', 'Presumed Innocent', 'Blood Work',
       'Hide &amp; Seek', 'Unspeakable', 'Saving Faith',
       'J Is for Judgment',
       'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
       'Misery', 'Dolores Claiborne', 'The Edge',
       'Heaven and Earth (Three Sisters Island Trilogy)', 'Hemlock Bay',
       'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
       'Where the Red Fern Grows',
       'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
       'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
       'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
       'Long After Midnight', 'One Door Away from Heaven',
       'By the Light of the Moon', 'Two for the Dough',
       'The God of Small Things', 'A Year in Provence',
       'Midnight in the Garden of Good and Evil', 'The Sands of Time',
       'If Only It Were True', 'Pay It Forward', "The Kitchen God's Wife",
       'Saint Maybe', 'A Patchwork Planet',
       'Tears of the Giraffe (No.1 Ladies Detective Agency)',
       "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
       'Balzac and the Little Chinese Seamstress : A Novel',
       'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
       "Hornet's Nest", '2nd Chance',
       'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
       'Small Town Girl', 'Still Waters',
       'A Thin Dark Line (Mysteries &amp; Horror)',
       'The Queen of the Damned (Vampire Chronicles (Paperback))',
       'Night Prey', 'Chromosome 6', 'Point of Origin', 'The Testament',
       'When the Wind Blows',
       "A Thousand Acres (Ballantine Reader's Circle)", 'Ashes to Ashes',
       'Fear Nothing', 'Seize the Night', "I'll Be Seeing You",
       'The Five People You Meet in Heaven', 'All I Really Need to Know',
       'Fried Green Tomatoes at the Whistle Stop Cafe',
       "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
       "Charlotte's Web (Trophy Newbery)", 'Good in Bed', 'Bleachers',
       'The Reader', 'The Diary of Ellen Rimbauer: My Life at Rose Red',
       'Disclosure', 'The Thorn Birds', 'The Runaway Jury',
       'WLD ACCORDNG GARP', "Don't Stand Too Close to a Naked Man",
       'Dark Rivers of the Heart', 'Whirlwind (Tyler, Book 1)',
       'Rainbow Six', 'Shadow Prey',
       'The Sum of All Fears (Jack Ryan Novels)',
       "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
       'A Time to Kill', 'Heartbeat', 'The Client', 'The Pelican Brief',
       "Smilla's Sense of Snow", 'The Horse Whisperer', 'Pet Sematary',
       'Four Past Midnight', 'Fat Tuesday', 'Hideaway',
       "We'll Meet Again", 'Mercy',
       'Sea Swept (Quinn Brothers (Paperback))',
       'The Shipping News : A Novel', 'The Catcher in the Rye',
       'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
       'Black House', 'The Gunslinger (The Dark Tower, Book 1)',
       'The Drawing of the Three (The Dark Tower, Book 2)',
       'Wizard and Glass (The Dark Tower, Book 4)', "The Handmaid's Tale",
       'Beloved (Plume Contemporary Fiction)',
       'Seabiscuit: An American Legend', 'The Smoke Jumper',
       'Drowning Ruth', 'Night', 'The Bean Trees', 'Rebecca',
       'The Surgeon', 'Neverwhere', 'Snow Falling on Cedars', 'Angels',
       'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       "Where the Heart Is (Oprah's Book Club (Paperback))",
       'The Honk and Holler Opening Soon', 'Summer Sisters',
       'Without Remorse', 'Bastard Out of Carolina', 'Sole Survivor',
       'The Switch', 'Intensity',
       'A Heartbreaking Work of Staggering Genius',
       'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
       'Circle of Friends', "Dude, Where's My Country?",
       'The Virgin Suicides',
       'Midnight in the Garden of Good and Evil: A Savannah Story',
       'It Was on Fire When I Lay Down on It', 'Blessings',
       'Falling Angels', 'Tis: A Memoir',
       'Fall On Your Knees (Oprah #45)', 'Welcome to Temptation',
       'Faking It', 'Scarlet Feather', 'Rising Tides',
       'Inner Harbor (Quinn Brothers (Paperback))',
       'Key of Light (Key Trilogy (Paperback))',
       'Key of Knowledge (Key Trilogy (Paperback))',
       'Key of Valor (Roberts, Nora. Key Trilogy, 3.)', 'Birthright',
       'The Empty Chair', 'The Woman Next Door', 'Sphere',
       'The Andromeda Strain', 'Congo', 'Rising Sun', 'Airframe',
       'The Lost World', 'Timeline', 'Paradise', "ANGELA'S ASHES",
       "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
       'A Bend in the Road', 'Winter Moon', 'Red Dragon',
       'Absolute Power', 'Last Man Standing',
       'The Bridges of Madison County', 'Different Seasons',
       'A Widow for One Year', 'P Is for Peril', 'Carolina Moon',
       'A Day Late and a Dollar Short', 'Guilty as Sin', 'Secret History',
       "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
       'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
       'The Wedding', 'About a Boy', 'House of Sand and Fog',
       'Five Quarters of the Orange', 'Interview with the Vampire',
       'Weep No More My Lady', 'Mirror Image', 'Tara Road',
       'The Guardian', 'Message in a Bottle',
       'Let Me Call You Sweetheart', 'While My Pretty One Sleeps',
       'Remember Me', 'Second Nature', 'The Last Precinct',
       'Isle of Dogs', 'Fatherhood', 'Debt of Honor (Jack Ryan Novels)',
       'One True Thing', 'The Simple Truth', 'Four Blind Mice',
       'STONES FROM THE RIVER', "Dr. Atkins' New Diet Revolution", '1984',
       'Evening Class', 'Drums of Autumn', 'Icy Sparks',
       "Drowning Ruth (Oprah's Book Club)", 'Engaging The Enemy',
       'Irish Hearts', 'Red Storm Rising', 'Echoes',
       'Nothing Lasts Forever', 'Smart Women', 'Temptation',
       'Truly, Madly Manhattan',
       "Sophie's World: A Novel About the History of Philosophy",
       'Cold Sassy Tree', 'Peace Like a River', 'Prime Cut',
       'At Home in Mitford (The Mitford Years)', 'Fast Women',
       'The Long Road Home', 'Standoff', 'Envy', 'Wish You Well',
       'Watership Down', 'Sick Puppy',
       'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
       'Nerd in Shining Armor', 'Outlander',
       'Face the Fire (Three Sisters Island Trilogy)',
       'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       'Harry Potter and the Goblet of Fire (Book 4)', 'The Robber Bride',
       'The Bachelor (Warner Books Contemporary Romance)',
       'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
       'The Little Prince', 'Coming Home',
       'The Vampire Lestat (Vampire Chronicles, Book II)', 'Beloved',
       "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
       "Foucault's Pendulum", 'Degree of Guilt', 'Icebound',
       'The Witching Hour (Lives of the Mayfair Witches)',
       'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
       'The Genesis Code', 'Ellen Foster', 'American Gods',
       "The Book of Ruth (Oprah's Book Club (Paperback))",
       'No Greater Love',
       'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
       'The Phantom Tollbooth', 'Dragon Tears', 'Midnight',
       'The Hunt for Red October', 'Turtle Moon', 'Fatal Cure',
       'The Body Farm', 'Acceptable Risk', 'Invasion', 'Sudden Prey',
       'Executive Orders (Jack Ryan Novels)', 'Purity in Death',
       'Family Album', 'Daddy', 'The Firm', 'A Wrinkle in Time',
       'Five Days in Paris', 'The Return Journey', 'The Kiss',
       'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
       "The General's Daughter", 'The Witness',
       'Slow Waltz in Cedar Bend', 'Primary Colors: A Novel of Politics',
       'Master of the Game', 'Catering to Nobody', 'Christine',
       'The Tommyknockers', 'Needful Things', "Gerald's Game",
       'The Door to December', 'A Case of Need', 'Insomnia',
       'The Deep End of the Ocean', 'The Reef',
       'Jewels of the Sun (Irish Trilogy)', "River's End",
       'Tears of the Moon (Irish Trilogy)',
       'Dance upon the Air (Three Sisters Island Trilogy)',
       'The Regulators', 'Couplehood',
       'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
       'The Clinic (Alex Delaware Novels (Paperback))',
       'Lake Wobegon Days', 'My Gal Sunday', 'Hearts In Atlantis',
       'Night Whispers', 'The Color Purple',
       'GARDEN OF SHADOWS (Dollanger Saga (Paperback))', 'Dawn (Cutler)',
       'Loves Music, Loves to Dance', 'Moonlight Becomes You',
       'If Tomorrow Comes', 'Dangerous', 'Call of the Wild',
       'In Her Shoes : A Novel', "Suzanne's Diary for Nicholas",
       'The Next Accident', 'Empire Falls', 'Easy Prey', 'Chosen Prey',
       'The Glass Lake', 'The Burden of Proof', '\\O\\" Is for Outlaw"',
       'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
       'The Killing Game: Only One Can Win...and the Loser Dies',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Plum Island', 'Final Target',
       'The Lottery Winner : Alvirah And Willy Stories',
       'The Subtle Knife (His Dark Materials, Book 2)',
       "The Girls' Guide to Hunting and Fishing",
       'High Five (A Stephanie Plum Novel)',
       'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       'Seven Up (A Stephanie Plum Novel)',
       'One for the Money (A Stephanie Plum Novel)',
       'The Mists of Avalon', 'The Loop', 'River, Cross My Heart',
       "A Virtuous Woman (Oprah's Book Club (Paperback))",
       "Vinegar Hill (Oprah's Book Club (Paperback))", 'The Rescue',
       'We Were the Mulvaneys',
       'A Man Named Dave: A Story of Triumph and Forgiveness',
       "The Clan of the Cave Bear (Earth's Children (Paperback))",
       'Jewel', 'Possession : A Romance', 'Riptide',
       'Digital Fortress : A Thriller', 'N Is for Noose',
       'The Summerhouse',
       'Chicken Soup for the Soul (Chicken Soup for the Soul)',
       'Here on Earth', 'M Is for Malice', 'The Cider House Rules',
       'Brave New World', 'Pigs in Heaven', 'Pride and Prejudice',
       'From the Corner of His Eye', 'Seabiscuit',
       "Pretend You Don't See Her", 'The Alibi', 'Before I Say Good-Bye',
       'Atonement : A Novel', 'Contact',
       'Plainsong (Vintage Contemporaries)', 'A Map of the World',
       'The Accidental Tourist', 'Unnatural Exposure', 'Deception Point',
       "Jewel (Oprah's Book Club)", 'Tis : A Memoir',
       'Wicked: The Life and Times of the Wicked Witch of the West',
       'The Alchemist: A Fable About Following Your Dream',
       'Bridget Jones: The Edge of Reason', 'The Hours: A Novel',
       'The Amber Spyglass (His Dark Materials, Book 3)',
       'The Golden Compass (His Dark Materials, Book 1)',
       'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
       'Good Omens', 'Animal Farm', 'The Valley of Horses', 'Sacred Sins',
       'The Two Towers (The Lord of the Rings, Part 2)',
       'The Perfect Storm : A True Story of Men Against the Sea',
       'Heart of the Sea (Irish Trilogy)', 'Black and Blue',
       'Nickel and Dimed: On (Not) Getting By in America',
       "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
       'The Nanny Diaries: A Novel', 'Three Junes', 'Strangers',
       "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
       "Angela's Ashes: A Memoir",
       "The Color of Water: A Black Man's Tribute to His White Mother",
       'The Mummy or Ramses the Damned',
       'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
       'Fast Food Nation: The Dark Side of the All-American Meal',
       'Daisy Fay and the Miracle Man', 'Cry Wolf', 'The Ugly Duckling',
       'Dust to Dust', 'Touching Evil', 'The Hours : A Novel',
       'Skipping Christmas', 'The Villa', 'Nights in Rodanthe',
       'Welcome to the World, Baby Girl!', 'FORREST GUMP (Movie Tie in)',
       'The Giver (21st Century Reference)', 'Charming Billy',
       'Granny Dan', 'Toxin', 'The Bad Place', 'Wuthering Heights',
       'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
       'The Carousel', 'Dragonfly in Amber', 'The House of the Spirits',
       'Kiss the Girls', 'Jurassic Park', 'Bridge to Terabithia',
       'Stanislaski Brothers (Silhouette Promo)', 'Three Fates',
       'Forever... : A Novel of Good and Evil, Love and Hope',
       'Seven Habits Of Highly Effective People', 'Mother of Pearl',
       'Anne Frank: The Diary of a Young Girl',
       'Confessions of a Shopaholic (Summer Display Opportunity)',
       'Shopaholic Takes Manhattan (Summer Display Opportunity)',
       'Breath, Eyes, Memory', 'How to Make an American Quilt',
       'Cold Mountain : A Novel', 'A Civil Action',
       'The Blue Nowhere : A Novel', 'I Capture the Castle',
       "What to Expect When You're Expecting (Revised Edition)",
       "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
       'Miss Julia Speaks Her Mind : A Novel',
       'Notes from a Small Island', 'Harvest', 'The Poisonwood Bible',
       'Year of Wonders', 'Pop Goes the Weasel',
       "Everything's Eventual : 14 Dark Tales", "CAT'S EYE",
       'Body of Lies', 'Now You See Her',
       'Jemima J: A Novel About Ugly Ducklings and Swans',
       'Sea Glass: A Novel', 'The Copper Beech',
       'Dying for Chocolate (Culinary Mysteries (Paperback))',
       'Clear and Present Danger (Jack Ryan Novels)',
       'The Return of the King (The Lord of the Rings, Part 3)',
       'The First Counsel', 'Watermelon',
       'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
       'How to Be Good', 'Carnal Innocence', 'You Belong To Me',
       'Confessions of an Ugly Stepsister : A Novel', 'It',
       'Midnight Bayou', 'Wifey', 'Montana Sky', 'Homecoming', 'Phantoms',
       'The Eight', 'The Gift', 'The Bourne Ultimatum',
       'The Eyre Affair: A Novel', 'Mr. Murder', 'Midwives: A Novel',
       'The Hundred Secret Senses',
       "Song of Solomon (Oprah's Book Club (Paperback))",
       'To the Nines: A Stephanie Plum Novel',
       'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',
       "It's Always Something", 'Tales of a Fourth Grade Nothing',
       'Animal Dreams',
       'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
       'A Fine Balance', 'Stillwatch', 'Slammerkin',
       "The Plains of Passage (Earth's Children (Paperback))",
       'Desperation',
       'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
       'Pleading Guilty', '4 Blondes', 'The Great Gatsby',
       'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
       'Last Chance Saloon', 'The Talisman',
       'Nicolae: The Rise of Antichrist (Left Behind No. 3)',

In [120]:
pickle.dump(books_with_tags.to_dict(),open("books_dict.pkl", "wb"))

In [121]:
pickle.dump(similarity,open("similarity.pkl","wb"))

In [122]:
famous_books

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books
184,278418,038550120X,0,A Painted House,JOHN GRISHAM,2001,Doubleday
368,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group
616,8681,0553561618,0,Dark Paradise,TAMI HOAG,1994,Bantam
750,278418,055356451X,0,Night Sins,TAMI HOAG,1995,Bantam
...,...,...,...,...,...,...,...
457242,11676,0345413865,0,Billy Straight : A Novel,JONATHAN KELLERMAN,1999,Ballantine Books
458903,11676,0373483694,0,Macgregor Grooms (Macgregors),Nora Roberts,1998,Silhouette
465107,11676,0399144714,9,Vector,Robin Cook,1999,Putnam Pub Group
479476,11676,0553278029,8,A Great Deliverance,Elizabeth George,1989,Bantam Books
489034,11676,0743418131,0,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket